name = "remix-vite-6"
compatibility_date = "2024-05-28"
pages_build_output_dir = "./dist/pages"

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "Counter"
script_name = "remix-vite-6-durable-objects"
