name = "remix-vite-6-durable-objects"
compatibility_date = "2024-05-28"
main = "./build/client/_worker.js/index.js"

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "Counter"

[[migrations]]
tag = "v1"
new_classes = ["Counter"]
