name: Deploy Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy Durable Objects
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 574fdb1eae7e80782a805c4b92f6b626
          wranglerVersion: "3.60.3"
          command: deploy --config wrangler.do.toml build/pages/_worker.js
        if: ${{ github.ref == 'refs/heads/main' }}
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 574fdb1eae7e80782a805c4b92f6b626
          projectName: remix-cf-vite-6
          workingDirectory: site
          directory: dist
          wranglerVersion: "3.60.3"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
